development: 
  adapter: postgresql 
  database: allowance_development 
  encoding: unicode 
  user: action 
  host: localhost 
  pool: 5 
  timeout: 5000


test:
  adapter: postgresql 
  database: allowance_test
  encoding: unicode 
  user: action 
  host: localhost 
  pool: 5 
  timeout: 5000

production:
  adapter: postgresql 
  database: allowance_production
  encoding: unicode 
  pool: 5 
  timeout: 5000